### ISSUE TITLE
SBP - Milestone 1

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#120]
This is a breakdown from the original [Milestone Document](https://drive.google.com/drive/u/0/folders/1UfFyq-HCtvmKfpAZBiuJ-KFIjf7yg1b6)

- [ ] Substrate pallet integration with IPFS
- [ ] Tests for integration with IPFS
- [ ] React Native Mobile app design
- [ ] Improve front-end integration tests (Cypress)
