### ISSUE TITLE
SBP - Milestone 2

### ISSUE THREAD

**Issue by stojanov-igor** [UniversalDot/UniversalDot-node#121]
This is a breakdown from the original [Milestone Document](https://drive.google.com/drive/u/0/folders/1UfFyq-HCtvmKfpAZBiuJ-KFIjf7yg1b6)

- [ ] Complete Integration with Tensorflow
- [ ] Feature Complete application
- [ ] Release v1
- [ ] Deployment of nodes
